pipeline
{
    agent any
    {
        stages
        {
                stage('Hello')
                {
                    steps
                    {
                        helloMethod()
                    }
                }
                stage('checkout')
                {
                    steps
                    {
                        checkout()
                    }
                }

        }
    }
}

